name: Request a Feature
description: Request a new feature or a change to an existing one.
labels: [ "feature" ]
body:
  - type: input
    id: version
    attributes:
      label: Geode Version
      description: The version of Geode you are using for suggesting a feature on. If you do not know where to find this, look for the mods listing.
      placeholder: "Example: v0.5.4"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: If the feature you wish to change is related to a problem, please describe it. Leave this field blank if it is not related to a problem.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Your Solution
      description: Describe the solution you would like to have happen.
      placeholder: "Example: If I could..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely achievable by doing X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request.
