name: Setup Ninja
description: Sets up Ninja

inputs:
  host:
    description: 'Host platform: win, mac or linux'
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup
    shell: bash
    run: |
      curl -L https://github.com/ninja-build/ninja/releases/latest/download/ninja-${{ inputs.host }}.zip -o ninja.zip
      7z x ninja.zip -o"$GITHUB_WORKSPACE/ninja"
      echo "$GITHUB_WORKSPACE/ninja" >> $GITHUB_PATH
