name: Setup Geode CLI
description: Sets up Geode CLI

inputs:
  host:
    description: 'Host platform: win, mac or linux'
    required: true

runs:
  using: "composite"
  steps:
  - name: Download
    uses: robinraju/release-downloader@v1.10
    with:
      repository: geode-sdk/cli
      tag: 'nightly'
      fileName: '*-${{ inputs.host }}.zip'
      tarBall: false
      zipBall: false
      out-file-path: "cli"

  - name: Setup
    shell: bash
    run: |
      7z x "cli/*-${{ inputs.host }}.zip" -ocli
      chmod +x cli/geode
      echo "$GITHUB_WORKSPACE/cli" >> $GITHUB_PATH
