if (NOT DEFINED GEODE_TARGET_PLATFORM)
	if(APPLE)
		if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
			set(GEODE_TARGET_PLATFORM "iOS")
		else()
			set(GEODE_TARGET_PLATFORM "MacOS")
		endif()
	elseif(WIN32)
		set(GEODE_TARGET_PLATFORM "Win32")
	else()
		message(FATAL_ERROR "Unable to detect platform, please set GEODE_TARGET_PLATFORM in the root CMake file.")
	endif()
endif()

if (GEODE_TARGET_PLATFORM STREQUAL "iOS")
	set(CMAKE_OSX_ARCHITECTURES arm64)
	set(CMAKE_OSX_SYSROOT ${GEODE_IOS_SDK})
endif()

include(${GEODE_SDK_PATH}/cmake/${GEODE_TARGET_PLATFORM}.cmake)