name: Check Changelog

on:
  push:
    paths:
      - 'CHANGELOG.md'
  pull_request:
    paths:
      - 'CHANGELOG.md'

jobs:
  check:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check for non-ASCII characters in changelog
        run: |
          if grep -q -P -n "[\x80-\xFF]" CHANGELOG.md; then
            echo "Non-ASCII characters found in CHANGELOG.md"
            exit 1
          else
            echo "No non-ASCII characters found in CHANGELOG.md"
          fi
