name: Update Website

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger site build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build workflow on geode-sdk/website repository
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'geode-sdk',
              repo: 'website',
              workflow_id: 'build.yml',
              ref: 'main'
            })
